# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ :name => 'Chicago' }, { :name => 'Copenhagen' }])
#   Mayor.create(:name => 'Emanuel', :city => cities.first)

[
  { :code => 'A', :description => 'Arts, Culture and Humanities' },
  { :code => 'B', :description => 'Educational Institutions and Related Activities' },
  { :code => 'C', :description => 'Environmental Quality, Protection and Beautification' },
  { :code => 'D', :description => 'Animal-Related' },
  { :code => 'E', :description => 'Health – General and Rehabilitative' },
  { :code => 'F', :description => 'Mental Health, Crisis Intervention' },
  { :code => 'G', :description => 'Diseases, Disorders, Medical Disciplines' },
  { :code => 'H', :description => 'Medical Research' },
  { :code => 'I', :description => 'Crime, Legal-Related' },
  { :code => 'J', :description => 'Employment, Job-Related' },
  { :code => 'K', :description => 'Food, Agriculture and Nutrition' },
  { :code => 'L', :description => 'Housing, Shelter' },
  { :code => 'M', :description => 'Public Safety, Disaster Preparedness and Relief' },
  { :code => 'N', :description => 'Recreation, Sports, Leisure, Athletics' },
  { :code => 'O', :description => 'Youth Development' },
  { :code => 'P', :description => 'Human Services – Multipurpose and Other' },
  { :code => 'Q', :description => 'International, Foreign Affairs and National Security' },
  { :code => 'R', :description => 'Civil Rights, Social Action, Advocacy' },
  { :code => 'S', :description => 'Community Improvement, Capacity Building' },
  { :code => 'T', :description => 'Philanthropy, Voluntarism and Grantmaking Foundations' },
  { :code => 'U', :description => 'Science and Technology Research Institutes, Services' },
  { :code => 'V', :description => 'Social Science Research Institutes, Services' },
  { :code => 'W', :description => 'Public, Society Benefit – Multipurpose and Other' },
  { :code => 'X', :description => 'Religion-Related, Spiritual Development' },
  { :code => 'Y', :description => 'Mutual/Membership Benefit Organizations, Other' },
  { :code => 'Z', :description => 'Unknown' }
].map do |common_code|
  CommonCode.create common_code
end

[
  { :code => 'A01', :description => "Alliance/Advocacy Organizations" },
  { :code => 'A02', :description => "Management & Technical Assistance" },
  { :code => 'A03', :description => "Professional Societies, Associations " },
  { :code => 'A05', :description => "Research Institutes and/or Public Policy Analysis" },
  { :code => 'A11', :description => "Single Organization Support" },
  { :code => 'A12', :description => "Fund Raising and/or Fund Distribution" },
  { :code => 'A19', :description => "Nonmonetary Support N.E.C.*" },
  { :code => 'A20', :description => "Arts, Cultural Organizations - Multipurpose" },
  { :code => 'A23', :description => "Cultural, Ethnic Awareness" },
  { :code => 'A25', :description => "Arts Education" },
  { :code => 'A26', :description => "Arts Council/Agency" },
  { :code => 'A30', :description => "Media, Communications Organizations" },
  { :code => 'A31', :description => "Film, Video" },
  { :code => 'A32', :description => "Television" },
  { :code => 'A33', :description => "Printing, Publishing" },
  { :code => 'A34', :description => "Radio" },
  { :code => 'A40', :description => "Visual Arts Organizations" },
  { :code => 'A50', :description => "Museum, Museum Activities" },
  { :code => 'A51', :description => "Art Museums" },
  { :code => 'A52', :description => "Children's Museums" },
  { :code => 'A54', :description => "History Museums" },
  { :code => 'A56', :description => "Natural History, Natural Science Museums" },
  { :code => 'A57', :description => "Science and Technology Museums" },
  { :code => 'A60', :description => "Performing Arts Organizations" },
  { :code => 'A61', :description => "Performing Arts Centers" },
  { :code => 'A62', :description => "Dance" },
  { :code => 'A63', :description => "Ballet" },
  { :code => 'A65', :description => "Theater" },
  { :code => 'A68', :description => "Music" },
  { :code => 'A69', :description => "Symphony Orchestras" },
  { :code => 'A6A', :description => "Opera" },
  { :code => 'A6B', :description => "Singing, Choral" },
  { :code => 'A6C', :description => "Music Groups, Bands, Ensembles" },
  { :code => 'A6E', :description => "Performing Arts Schools" },
  { :code => 'A70', :description => "Humanities Organizations         " },
  { :code => 'A80', :description => "Historical Societies, Related Historical Activities" },
  { :code => 'A84', :description => "Commemorative Events" },
  { :code => 'A90', :description => "Arts Service Organizations and Activities" },
  { :code => 'A99', :description => "Arts, Culture, and Humanities N.E.C." },
  { :code => 'B01', :description => "Alliance/Advocacy Organizations          " },
  { :code => 'B02', :description => "Management & Technical Assistance          " },
  { :code => 'B03', :description => "Professional Societies, Associations " },
  { :code => 'B05', :description => "Research Institutes and/or Public Policy Analysis " },
  { :code => 'B11', :description => "Single Organization Support " },
  { :code => 'B12', :description => "Fund Raising and/or Fund Distribution " },
  { :code => 'B19', :description => "Nonmonetary Support N.E.C." },
  { :code => 'B20', :description => "Elementary, Secondary Education, K - 12" },
  { :code => 'B21', :description => "Kindergarten, Preschool, Nursery School, Early Admissions" },
  { :code => 'B24', :description => "Primary, Elementary Schools" },
  { :code => 'B25', :description => "Secondary, High School" },
  { :code => 'B28', :description => "Specialized Education Institutions" },
  { :code => 'B30', :description => "Vocational, Technical Schools" },
  { :code => 'B40', :description => "Higher Education Institutions" },
  { :code => 'B41', :description => "Community or Junior Colleges" },
  { :code => 'B42', :description => "Undergraduate College (4-year)" },
  { :code => 'B43', :description => "University or Technological Institute" },
  { :code => 'B50', :description => "Graduate, Professional Schools (Separate Entities)" },
  { :code => 'B60', :description => "Adult, Continuing Education" },
  { :code => 'B70', :description => "Libraries" },
  { :code => 'B80', :description => "Student Services, Organizations of Students" },
  { :code => 'B82', :description => "Scholarships, Student Financial Aid Services, Awards" },
  { :code => 'B83', :description => "Student Sororities, Fraternities" },
  { :code => 'B84', :description => "Alumni Associations" },
  { :code => 'B90', :description => "Educational Services and Schools - Other" },
  { :code => 'B92', :description => "Remedial Reading, Reading Encouragement" },
  { :code => 'B94', :description => "Parent/Teacher Group" },
  { :code => 'B99', :description => "Education N.E.C." },
  { :code => 'C01', :description => "Alliance/Advocacy Organizations          " },
  { :code => 'C02', :description => "Management & Technical Assistance          " },
  { :code => 'C03', :description => "Professional Societies, Associations          " },
  { :code => 'C05', :description => "Research Institutes and/or Public Policy Analysis " },
  { :code => 'C11', :description => "Single Organization Support " },
  { :code => 'C12', :description => "Fund Raising and/or Fund Distribution " },
  { :code => 'C19', :description => "Nonmonetary Support N.E.C." },
  { :code => 'C20', :description => "Pollution Abatement and Control Services" },
  { :code => 'C27', :description => "Recycling Programs" },
  { :code => 'C30', :description => "Natural Resources Conservation and Protection" },
  { :code => 'C32', :description => "Water Resource, Wetlands Conservation and Management" },
  { :code => 'C34', :description => "Land Resources Conservation" },
  { :code => 'C35', :description => "Energy Resources Conservation and Development" },
  { :code => 'C36', :description => "Forest Conservation" },
  { :code => 'C40', :description => "Botanical, Horticultural, and Landscape Services" },
  { :code => 'C41', :description => "Botanical Gardens, Arboreta and Botanical Organizations" },
  { :code => 'C42', :description => "Garden Club, Horticultural Program" },
  { :code => 'C50', :description => "Environmental Beautification and Aesthetics" },
  { :code => 'C60', :description => "Environmental Education and Outdoor Survival Programs" },
  { :code => 'C99', :description => "Environmental Quality, Protection, and Beautification N.E.C." },
  { :code => 'D01', :description => "Alliance/Advocacy Organizations " },
  { :code => 'D02', :description => "Management & Technical Assistance " },
  { :code => 'D03', :description => "Professional Societies, Associations " },
  { :code => 'D05', :description => "Research Institutes and/or Public Policy Analysis " },
  { :code => 'D11', :description => "Single Organization Support " },
  { :code => 'D12', :description => "Fund Raising and/or Fund Distribution " },
  { :code => 'D19', :description => "Nonmonetary Support N.E.C." },
  { :code => 'D20', :description => "Animal Protection and Welfare" },
  { :code => 'D30', :description => "Wildlife Preservation, Protection" },
  { :code => 'D31', :description => "Protection of Endangered Species" },
  { :code => 'D32', :description => "Bird Sanctuary, Preserve" },
  { :code => 'D33', :description => "Fisheries Resources" },
  { :code => 'D34', :description => "Wildlife Sanctuary, Refuge" },
  { :code => 'D40', :description => "Veterinary Services" },
  { :code => 'D50', :description => "Zoo, Zoological Society" },
  { :code => 'D60', :description => "Other Services - Specialty Animals" },
  { :code => 'D61', :description => "Animal Training, Behavior" },
  { :code => 'D99', :description => "Animal-Related N.E.C." },
  { :code => 'E01', :description => "Alliance/Advocacy Organizations          " },
  { :code => 'E02', :description => "Management & Technical Assistance " },
  { :code => 'E03', :description => "Professional Societies, Associations " },
  { :code => 'E05', :description => "Research Institutes and/or Public Policy Analysis " },
  { :code => 'E11', :description => "Single Organization Support " },
  { :code => 'E12', :description => "Fund Raising and/or Fund Distribution " },
  { :code => 'E19', :description => "Nonmonetary Support N.E.C." },
  { :code => 'E20', :description => "Hospitals and Related Primary Medical Care Facilities" },
  { :code => 'E21', :description => "Community Health Systems" },
  { :code => 'E22', :description => "Hospital, General" },
  { :code => 'E24', :description => "Hospital, Specialty" },
  { :code => 'E30', :description => "Health Treatment Facilities, Primarily Outpatient" },
  { :code => 'E31', :description => "Group Health Practice (Health Maintenance Organizations)" },
  { :code => 'E32', :description => "Ambulatory Health Center, Community Clinic" },
  { :code => 'E40', :description => "Reproductive Health Care Facilities and Allied Services" },
  { :code => 'E42', :description => "Family Planning Centers" },
  { :code => 'E50', :description => "Rehabilitative Medical Services" },
  { :code => 'E60', :description => "Health Support Services" },
  { :code => 'E61', :description => "Blood Supply Related" },
  { :code => 'E62', :description => "Ambulance, Emergency Medical Transport Services" },
  { :code => 'E65', :description => "Organ and Tissue Banks" },
  { :code => 'E70', :description => "Public Health Program (Includes General Health and Wellness Promotion Services)" },
  { :code => 'E80', :description => "Health, General and Financing" },
  { :code => 'E86', :description => "Patient Services - Entertainment, Recreation" },
  { :code => 'E90', :description => "Nursing Services (General)" },
  { :code => 'E91', :description => "Nursing, Convalescent Facilities" },
  { :code => 'E92', :description => "Home Health Care" },
  { :code => 'E99', :description => "Health - General and Rehabilitative N.E.C." },
  { :code => 'F01', :description => "Alliance/Advocacy Organizations          " },
  { :code => 'F02', :description => "Management & Technical Assistance " },
  { :code => 'F03', :description => "Professional Societies, Associations " },
  { :code => 'F05', :description => "Research Institutes and/or Public Policy Analysis " },
  { :code => 'F11', :description => "Single Organization Support " },
  { :code => 'F12', :description => "Fund Raising and/or Fund Distribution " },
  { :code => 'F19', :description => "Nonmonetary Support N.E.C." },
  { :code => 'F20', :description => "Alcohol, Drug and Substance Abuse, Dependency Prevention and Treatment" },
  { :code => 'F21', :description => "Alcohol, Drug Abuse, Prevention Only" },
  { :code => 'F22', :description => "Alcohol, Drug Abuse, Treatment Only" },
  { :code => 'F30', :description => "Mental Health Treatment - Multipurpose and N.E.C." },
  { :code => 'F31', :description => "Psychiatric, Mental Health Hospital" },
  { :code => 'F32', :description => "Community Mental Health Center" },
  { :code => 'F33', :description => "Group Home, Residential Treatment Facility - Mental Health Related" },
  { :code => 'F40', :description => "Hot Line, Crisis Intervention Services" },
  { :code => 'F42', :description => "Rape Victim Services" },
  { :code => 'F50', :description => "Addictive Disorders N.E.C." },
  { :code => 'F52', :description => "Smoking Addiction" },
  { :code => 'F53', :description => "Eating Disorder, Addiction" },
  { :code => 'F54', :description => "Gambling Addiction" },
  { :code => 'F60', :description => "Counseling, Support Groups" },
  { :code => 'F70', :description => "Mental Health Disorders" },
  { :code => 'F80', :description => "Mental Health Association, Multipurpose" },
  { :code => 'F99', :description => "Mental Health, Crisis Intervention N.E.C." },
  { :code => 'G01', :description => "Alliance/Advocacy Organizations " },
  { :code => 'G02', :description => "Management & Technical Assistance " },
  { :code => 'G03', :description => "Professional Societies, Associations " },
  { :code => 'G05', :description => "Research Institutes and/or Public Policy Analysis " },
  { :code => 'G11', :description => "Single Organization Support " },
  { :code => 'G12', :description => "Fund Raising and/or Fund Distribution " },
  { :code => 'G19', :description => "Nonmonetary Support N.E.C." },
  { :code => 'G20', :description => "Birth Defects and Genetic Diseases" },
  { :code => 'G25', :description => "Down Syndrome" },
  { :code => 'G30', :description => "Cancer" },
  { :code => 'G40', :description => "Diseases of Specific Organs" },
  { :code => 'G41', :description => "Eye Diseases, Blindness and Vision Impairments" },
  { :code => 'G42', :description => "Ear and Throat Diseases" },
  { :code => 'G43', :description => "Heart and Circulatory System Diseases, Disorders" },
  { :code => 'G44', :description => "Kidney Disease" },
  { :code => 'G45', :description => "Lung Disease" },
  { :code => 'G48', :description => "Brain Disorders" },
  { :code => 'G50', :description => "Nerve, Muscle and Bone Diseases" },
  { :code => 'G51', :description => "Arthritis" },
  { :code => 'G54', :description => "Epilepsy" },
  { :code => 'G60', :description => "Allergy Related Diseases" },
  { :code => 'G61', :description => "Asthma" },
  { :code => 'G70', :description => "Digestive Diseases, Disorders" },
  { :code => 'G80', :description => "Specifically Named Diseases" },
  { :code => 'G81', :description => "AIDS" },
  { :code => 'G83', :description => "Alzheimer's Disease" },
  { :code => 'G84', :description => "Autism" },
  { :code => 'G90', :description => "Medical Disciplines" },
  { :code => 'G92', :description => "Biomedicine, Bioengineering " },
  { :code => 'G94', :description => "Geriatrics" },
  { :code => 'G96', :description => "Neurology, Neuroscience" },
  { :code => 'G98', :description => "Pediatrics" },
  { :code => 'G9B', :description => "Surgery" },
  { :code => 'G99', :description => "Diseases, Disorders, Medical Disciplines N.E.C." },
  { :code => 'H01', :description => "Alliance/Advocacy Organizations          " },
  { :code => 'H02', :description => "Management & Technical Assistance          " },
  { :code => 'H03', :description => "Professional Societies, Associations          " },
  { :code => 'H05', :description => "Research Institutes and/or Public Policy Analysis          " },
  { :code => 'H11', :description => "Single Organization Support " },
  { :code => 'H12', :description => "Fund Raising and/or Fund Distribution " },
  { :code => 'H19', :description => "Nonmonetary Support N.E.C." },
  { :code => 'H20', :description => "Birth Defects, Genetic Diseases Research" },
  { :code => 'H25', :description => "Down Syndrome Research" },
  { :code => 'H30', :description => "Cancer Research" },
  { :code => 'H40', :description => "Specific Organ Research" },
  { :code => 'H41', :description => "Eye Research" },
  { :code => 'H42', :description => "Ear and Throat Research" },
  { :code => 'H43', :description => "Heart, Circulatory Research" },
  { :code => 'H44', :description => "Kidney Research" },
  { :code => 'H45', :description => "Lung Research" },
  { :code => 'H48', :description => "Brain Disorders Research" },
  { :code => 'H50', :description => "Nerve, Muscle, Bone Research" },
  { :code => 'H51', :description => "Arthritis Research" },
  { :code => 'H54', :description => "Epilepsy Research" },
  { :code => 'H60', :description => "Allergy Related Disease Research" },
  { :code => 'H61', :description => "Asthma Research" },
  { :code => 'H70', :description => "Digestive Disease, Disorder Research" },
  { :code => 'H80', :description => "Specifically Named Diseases Research" },
  { :code => 'H81', :description => "AIDS Research" },
  { :code => 'H83', :description => "Alzheimer's Disease Research" },
  { :code => 'H84', :description => "Autism Research" },
  { :code => 'H90', :description => "Medical Specialty Research" },
  { :code => 'H92', :description => "Biomedicine, Bioengineering Research" },
  { :code => 'H94', :description => "Geriatrics Research" },
  { :code => 'H96', :description => "Neurology, Neuroscience Research" },
  { :code => 'H98', :description => "Pediatrics Research" },
  { :code => 'H9B', :description => "Surgery Research" },
  { :code => 'H99', :description => "Medical Research N.E.C." },
  { :code => 'I01', :description => "Alliance/Advocacy Organizations          " },
  { :code => 'I02', :description => "Management & Technical Assistance " },
  { :code => 'I03', :description => "Professional Societies, Associations " },
  { :code => 'I05', :description => "Research Institutes and/or Public Policy Analysis " },
  { :code => 'I11', :description => "Single Organization Support " },
  { :code => 'I12', :description => "Fund Raising and/or Fund Distribution " },
  { :code => 'I19', :description => "Nonmonetary Support N.E.C." },
  { :code => 'I20', :description => "Crime Prevention N.E.C." },
  { :code => 'I21', :description => "Delinquency Prevention" },
  { :code => 'I23', :description => "Drunk Driving Related" },
  { :code => 'I30', :description => "Correctional Facilities N.E.C." },
  { :code => 'I31', :description => "Transitional Care, Half-Way House for Offenders, Ex-Offenders" },
  { :code => 'I40', :description => "Rehabilitation Services for Offenders" },
  { :code => 'I43', :description => "Services to Prisoners and Families - Multipurpose" },
  { :code => 'I44', :description => "Prison Alternatives" },
  { :code => 'I50', :description => "Administration of Justice, Courts" },
  { :code => 'I51', :description => "Dispute Resolution, Mediation Services" },
  { :code => 'I60', :description => "Law Enforcement Agencies (Police Departments)" },
  { :code => 'I70', :description => "Protection Against, Prevention of Neglect, Abuse, Exploitation" },
  { :code => 'I71', :description => "Spouse Abuse, Prevention of" },
  { :code => 'I72', :description => "Child Abuse, Prevention of" },
  { :code => 'I73', :description => "Sexual Abuse, Prevention of" },
  { :code => 'I80', :description => "Legal Services" },
  { :code => 'I83', :description => "Public Interest Law, Litigation" },
  { :code => 'I99', :description => "Crime, Legal Related N.E.C." },
  { :code => 'J01', :description => "Alliance/Advocacy Organizations " },
  { :code => 'J02', :description => "Management & Technical Assistance " },
  { :code => 'J03', :description => "Professional Societies, Associations " },
  { :code => 'J05', :description => "Research Institutes and/or Public Policy Analysis " },
  { :code => 'J11', :description => "Single Organization Support " },
  { :code => 'J12', :description => "Fund Raising and/or Fund Distribution " },
  { :code => 'J19', :description => "Nonmonetary Support N.E.C." },
  { :code => 'J20', :description => "Employment Procurement Assistance, Job Training" },
  { :code => 'J21', :description => "Vocational Counseling, Guidance and Testing" },
  { :code => 'J22', :description => "Vocational Training" },
  { :code => 'J30', :description => "Vocational Rehabilitation" },
  { :code => 'J32', :description => "Goodwill Industries" },
  { :code => 'J33', :description => "Sheltered Remunerative Employment, Work Activity Center N.E.C." },
  { :code => 'J40', :description => "Labor Unions, Organizations" },
  { :code => 'J99', :description => "Employment, Job Related N.E.C." },
  { :code => 'K01', :description => "Alliance/Advocacy Organizations          " },
  { :code => 'K02', :description => "Management & Technical Assistance          " },
  { :code => 'K03', :description => "Professional Societies, Associations          " },
  { :code => 'K05', :description => "Research Institutes and/or Public Policy Analysis " },
  { :code => 'K11', :description => "Single Organization Support " },
  { :code => 'K12', :description => "Fund Raising and/or Fund Distribution " },
  { :code => 'K19', :description => "Nonmonetary Support N.E.C." },
  { :code => 'K20', :description => "Agricultural Programs" },
  { :code => 'K25', :description => "Farmland Preservation" },
  { :code => 'K26', :description => "Livestock Breeding, Development, Management" },
  { :code => 'K28', :description => "Farm Bureau, Grange" },
  { :code => 'K30', :description => "Food Service, Free Food Distribution Programs" },
  { :code => 'K31', :description => "Food Banks, Food Pantries" },
  { :code => 'K34', :description => "Congregate Meals" },
  { :code => 'K35', :description => "Eatery, Agency, Organization Sponsored" },
  { :code => 'K36', :description => "Meals on Wheels" },
  { :code => 'K40', :description => "Nutrition Programs" },
  { :code => 'K50', :description => "Home Economics" },
  { :code => 'K99', :description => "Food, Agriculture, and Nutrition N.E.C." },
  { :code => 'L01', :description => "Alliance/Advocacy Organizations " },
  { :code => 'L02', :description => "Management & Technical Assistance " },
  { :code => 'L03', :description => "Professional Societies, Associations " },
  { :code => 'L05', :description => "Research Institutes and/or Public Policy Analysis " },
  { :code => 'L11', :description => "Single Organization Support " },
  { :code => 'L12', :description => "Fund Raising and/or Fund Distribution " },
  { :code => 'L19', :description => "Nonmonetary Support N.E.C." },
  { :code => 'L20', :description => "Housing Development, Construction, Management" },
  { :code => 'L21', :description => "Public Housing Facilities" },
  { :code => 'L22', :description => "Senior Citizens' Housing/Retirement Communities" },
  { :code => 'L25', :description => "Housing Rehabilitation" },
  { :code => 'L30', :description => "Housing Search Assistance" },
  { :code => 'L40', :description => "Low-Cost Temporary Housing" },
  { :code => 'L41', :description => "Homeless, Temporary Shelter For" },
  { :code => 'L50', :description => "Housing Owners, Renters Organizations" },
  { :code => 'L80', :description => "Housing Support Services -- Other" },
  { :code => 'L81', :description => "Home Improvement and Repairs" },
  { :code => 'L82', :description => "Housing Expense Reduction Support" },
  { :code => 'L99', :description => "Housing, Shelter N.E.C." },
  { :code => 'M01', :description => "Alliance/Advocacy Organizations  " },
  { :code => 'M02', :description => "Management & Technical Assistance          " },
  { :code => 'M03', :description => "Professional Societies, Associations " },
  { :code => 'M05', :description => "Research Institutes and/or Public Policy Analysis " },
  { :code => 'M11', :description => "Single Organization Support " },
  { :code => 'M12', :description => "Fund Raising and/or Fund Distribution " },
  { :code => 'M19', :description => "Nonmonetary Support N.E.C." },
  { :code => 'M20', :description => "Disaster Preparedness and Relief Services" },
  { :code => 'M23', :description => "Search and Rescue Squads, Services" },
  { :code => 'M24', :description => "Fire Prevention, Protection, Control" },
  { :code => 'M40', :description => "Safety Education" },
  { :code => 'M41', :description => "First Aid Training, Services" },
  { :code => 'M42', :description => "Automotive Safety" },
  { :code => 'M99', :description => "Public Safety, Disaster Preparedness, and Relief N.E.C." },
  { :code => 'N01', :description => "Alliance/Advocacy Organizations " },
  { :code => 'N02', :description => "Management & Technical Assistance " },
  { :code => 'N03', :description => "Professional Societies, Associations " },
  { :code => 'N05', :description => "Research Institutes and/or Public Policy Analysis " },
  { :code => 'N11', :description => "Single Organization Support " },
  { :code => 'N12', :description => "Fund Raising and/or Fund Distribution " },
  { :code => 'N19', :description => "Nonmonetary Support N.E.C." },
  { :code => 'N20', :description => "Recreational and Sporting Camps" },
  { :code => 'N30', :description => "Physical Fitness and Community Recreational Facilities" },
  { :code => 'N31', :description => "Community Recreational Centers" },
  { :code => 'N32', :description => "Parks and Playgrounds" },
  { :code => 'N40', :description => "Sports Training Facilities, Agencies" },
  { :code => 'N50', :description => "Recreational, Pleasure, or Social Club" },
  { :code => 'N52', :description => "Fairs, County and Other" },
  { :code => 'N60', :description => "Amateur Sports Clubs, Leagues, N.E.C." },
  { :code => 'N61', :description => "Fishing, Hunting Clubs" },
  { :code => 'N62', :description => "Basketball" },
  { :code => 'N63', :description => "Baseball, Softball" },
  { :code => 'N64', :description => "Soccer Clubs, Leagues" },
  { :code => 'N65', :description => "Football Clubs, Leagues" },
  { :code => 'N66', :description => "Tennis, Racquet Sports Clubs, Leagues" },
  { :code => 'N67', :description => "Swimming, Water Recreation" },
  { :code => 'N68', :description => "Winter Sports (Snow and Ice)" },
  { :code => 'N69', :description => "Equestrian, Riding" },
  { :code => 'N6A', :description => "Golf" },
  { :code => 'N70', :description => "Amateur Sports Competitions" },
  { :code => 'N71', :description => "Olympics Committees and Related International Competitions        " },
  { :code => 'N72', :description => "Special Olympics         " },
  { :code => 'N80', :description => "Professional Athletic Leagues" },
  { :code => 'N99', :description => "Recreation, Sports, Leisure, Athletics N.E.C." },
  { :code => 'O01', :description => "Alliance/Advocacy Organizations          " },
  { :code => 'O02', :description => "Management & Technical Assistance          " },
  { :code => 'O03', :description => "Professional Societies, Associations          " },
  { :code => 'O05', :description => "Research Institutes and/or Public Policy Analysis " },
  { :code => 'O11', :description => "Single Organization Support " },
  { :code => 'O12', :description => "Fund Raising and/or Fund Distribution " },
  { :code => 'O19', :description => "Nonmonetary Support N.E.C." },
  { :code => 'O20', :description => "Youth Centers, Clubs, Multipurpose" },
  { :code => 'O21', :description => "Boys Clubs" },
  { :code => 'O22', :description => "Girls Clubs" },
  { :code => 'O23', :description => "Boys and Girls Clubs (Combined)" },
  { :code => 'O30', :description => "Adult, Child Matching Programs" },
  { :code => 'O31', :description => "Big Brothers, Big Sisters" },
  { :code => 'O40', :description => "Scouting Organizations" },
  { :code => 'O41', :description => "Boy Scouts of America" },
  { :code => 'O42', :description => "Girl Scouts of the U.S.A." },
  { :code => 'O43', :description => "Camp Fire" },
  { :code => 'O50', :description => "Youth Development Programs, Other" },
  { :code => 'O51', :description => "Youth Community Service Clubs" },
  { :code => 'O52', :description => "Youth Development - Agricultural" },
  { :code => 'O53', :description => "Youth Development - Business" },
  { :code => 'O54', :description => "Youth Development - Citizenship Programs" },
  { :code => 'O55', :description => "Youth Development - Religious Leadership" },
  { :code => 'O99', :description => "Youth Development N.E.C." },
  { :code => 'P01', :description => "Alliance/Advocacy Organizations " },
  { :code => 'P02', :description => "Management & Technical Assistance " },
  { :code => 'P03', :description => "Professional Societies, Associations " },
  { :code => 'P05', :description => "Research Institutes and/or Public Policy Analysis " },
  { :code => 'P11', :description => "Single Organization Support " },
  { :code => 'P12', :description => "Fund Raising and/or Fund Distribution " },
  { :code => 'P19', :description => "Nonmonetary Support N.E.C." },
  { :code => 'P20', :description => "Human Service Organizations - Multipurpose" },
  { :code => 'P21', :description => "American Red Cross" },
  { :code => 'P22', :description => "Urban League" },
  { :code => 'P24', :description => "Salvation Army" },
  { :code => 'P26', :description => "Volunteers of America         " },
  { :code => 'P27', :description => "Young Men's or Women's Associations (YMCA, YWCA, YWHA, YMHA)         " },
  { :code => 'P28', :description => "Neighborhood Centers, Settlement Houses" },
  { :code => 'P29', :description => "Thrift Shops" },
  { :code => 'P30', :description => "Children's, Youth Services" },
  { :code => 'P31', :description => "Adoption" },
  { :code => 'P32', :description => "Foster Care" },
  { :code => 'P33', :description => "Child Day Care" },
  { :code => 'P40', :description => "Family Services" },
  { :code => 'P42', :description => "Single Parent Agencies, Services" },
  { :code => 'P43', :description => "Family Violence Shelters, Services" },
  { :code => 'P44', :description => "Homemaker, Home Health Aide" },
  { :code => 'P45', :description => "Family Services, Adolescent Parents" },
  { :code => 'P46', :description => "Family Counseling" },
  { :code => 'P50', :description => "Personal Social Services" },
  { :code => 'P51', :description => "Financial Counseling, Money Management" },
  { :code => 'P52', :description => "Transportation, Free or Subsidized" },
  { :code => 'P58', :description => "Gift Distribution" },
  { :code => 'P60', :description => "Emergency Assistance (Food, Clothing, Cash)" },
  { :code => 'P61', :description => "Travelers' Aid" },
  { :code => 'P62', :description => "Victims' Services" },
  { :code => 'P70', :description => "Residential, Custodial Care" },
  { :code => 'P72', :description => "Half-Way House (Short-Term Residential Care)" },
  { :code => 'P73', :description => "Group Home (Long Term)" },
  { :code => 'P74', :description => "Hospice" },
  { :code => 'P75', :description => "Senior Continuing Care Communities" },
  { :code => 'P80', :description => "Services to Promote the Independence of Specific Populations" },
  { :code => 'P81', :description => "Senior Centers, Services" },
  { :code => 'P82', :description => "Developmentally Disabled Centers, Services" },
  { :code => 'P84', :description => "Ethnic, Immigrant Centers, Services" },
  { :code => 'P85', :description => "Homeless Persons Centers, Services" },
  { :code => 'P86', :description => "Blind/Visually Impaired Centers, Services " },
  { :code => 'P87', :description => "Deaf/Hearing Impaired Centers, Services " },
  { :code => 'P99', :description => "Human Services - Multipurpose and Other N.E.C." },
  { :code => 'Q01', :description => "Alliance/Advocacy Organizations          " },
  { :code => 'Q02', :description => "Management & Technical Assistance          " },
  { :code => 'Q03', :description => "Professional Societies, Associations " },
  { :code => 'Q05', :description => "Research Institutes and/or Public Policy Analysis " },
  { :code => 'Q11', :description => "Single Organization Support " },
  { :code => 'Q12', :description => "Fund Raising and/or Fund Distribution " },
  { :code => 'Q19', :description => "Nonmonetary Support N.E.C." },
  { :code => 'Q20', :description => "Promotion of International Understanding" },
  { :code => 'Q21', :description => "International Cultural Exchange" },
  { :code => 'Q22', :description => "International Student Exchange and Aid" },
  { :code => 'Q23', :description => "International Exchanges, N.E.C." },
  { :code => 'Q30', :description => "International Development, Relief Services" },
  { :code => 'Q31', :description => "International Agricultural Development" },
  { :code => 'Q32', :description => "International Economic Development" },
  { :code => 'Q33', :description => "International Relief" },
  { :code => 'Q40', :description => "International Peace and Security" },
  { :code => 'Q41', :description => "Arms Control, Peace Organizations" },
  { :code => 'Q42', :description => "United Nations Association" },
  { :code => 'Q43', :description => "National Security, Domestic" },
  { :code => 'Q70', :description => "International Human Rights" },
  { :code => 'Q71', :description => "International Migration, Refugee Issues" },
  { :code => 'Q99', :description => "International, Foreign Affairs, and National Security N.E.C." },
  { :code => 'R01', :description => "Alliance/Advocacy Organizations " },
  { :code => 'R02', :description => "Management & Technical Assistance " },
  { :code => 'R03', :description => "Professional Societies, Associations " },
  { :code => 'R05', :description => "Research Institutes and/or Public Policy Analysis " },
  { :code => 'R11', :description => "Single Organization Support " },
  { :code => 'R12', :description => "Fund Raising and/or Fund Distribution " },
  { :code => 'R19', :description => "Nonmonetary Support N.E.C." },
  { :code => 'R20', :description => "Civil Rights, Advocacy for Specific Groups" },
  { :code => 'R22', :description => "Minority Rights" },
  { :code => 'R23', :description => "Disabled Persons' Rights" },
  { :code => 'R24', :description => "Women's Rights" },
  { :code => 'R25', :description => "Seniors' Rights" },
  { :code => 'R26', :description => "Lesbian, Gay Rights" },
  { :code => 'R30', :description => "Intergroup, Race Relations" },
  { :code => 'R40', :description => "Voter Education, Registration" },
  { :code => 'R60', :description => "Civil Liberties Advocacy" },
  { :code => 'R61', :description => "Reproductive Rights" },
  { :code => 'R62', :description => "Right to Life" },
  { :code => 'R63', :description => "Censorship, Freedom of Speech and Press Issues" },
  { :code => 'R67', :description => "Right to Die, Euthanasia Issues" },
  { :code => 'R99', :description => "Civil Rights, Social Action, Advocacy N.E.C." },
  { :code => 'S01', :description => "Alliance/Advocacy Organizations          " },
  { :code => 'S02', :description => "Management & Technical Assistance " },
  { :code => 'S03', :description => "Professional Societies, Associations " },
  { :code => 'S05', :description => "Research Institutes and/or Public Policy Analysis " },
  { :code => 'S11', :description => "Single Organization Support " },
  { :code => 'S12', :description => "Fund Raising and/or Fund Distribution " },
  { :code => 'S19', :description => "Nonmonetary Support N.E.C." },
  { :code => 'S20', :description => "Community, Neighborhood Development, Improvement (General)" },
  { :code => 'S21', :description => "Community Coalitions" },
  { :code => 'S22', :description => "Neighborhood, Block Associations" },
  { :code => 'S30', :description => "Economic Development" },
  { :code => 'S31', :description => "Urban, Community Economic Development" },
  { :code => 'S32', :description => "Rural Development" },
  { :code => 'S40', :description => "Business and Industry" },
  { :code => 'S41', :description => "Promotion of Business" },
  { :code => 'S43', :description => "Management Services for Small Business, Entrepreneurs" },
  { :code => 'S46', :description => "Boards of Trade" },
  { :code => 'S47', :description => "Real Estate Organizations" },
  { :code => 'S50', :description => "Nonprofit Management" },
  { :code => 'S80', :description => "Community Service Clubs" },
  { :code => 'S81', :description => "Women's Service Clubs" },
  { :code => 'S82', :description => "Men's Service Clubs" },
  { :code => 'S99', :description => "Community Improvement, Capacity Building N.E.C." },
  { :code => 'T01', :description => "Alliance/Advocacy Organizations " },
  { :code => 'T02', :description => "Management & Technical Assistance " },
  { :code => 'T03', :description => "Professional Societies, Associations " },
  { :code => 'T05', :description => "Research Institutes and/or Public Policy Analysis " },
  { :code => 'T11', :description => "Single Organization Support " },
  { :code => 'T12', :description => "Fund Raising and/or Fund Distribution " },
  { :code => 'T19', :description => "Nonmonetary Support N.E.C." },
  { :code => 'T20', :description => "Private Grantmaking Foundations" },
  { :code => 'T21', :description => "Corporate Foundations" },
  { :code => 'T22', :description => "Private Independent Foundations" },
  { :code => 'T23', :description => "Private Operating Foundations" },
  { :code => 'T30', :description => "Public Foundations" },
  { :code => 'T31', :description => "Community Foundations" },
  { :code => 'T40', :description => "Voluntarism Promotion" },
  { :code => 'T50', :description => "Philanthropy, Charity, Voluntarism Promotion, General" },
  { :code => 'T70', :description => "Fund Raising Organizations That Cross Categories" },
  { :code => 'T90', :description => "Named Trusts/Foundations N.E.C. " },
  { :code => 'T99', :description => "Philanthropy, Voluntarism, and Grantmaking Foundations N.E.C." },
  { :code => 'U01', :description => "Alliance/Advocacy Organizations          " },
  { :code => 'U02', :description => "Management & Technical Assistance          " },
  { :code => 'U03', :description => "Professional Societies, Associations          " },
  { :code => 'U05', :description => "Research Institutes and/or Public Policy Analysis " },
  { :code => 'U11', :description => "Single Organization Support " },
  { :code => 'U12', :description => "Fund Raising and/or Fund Distribution " },
  { :code => 'U19', :description => "Nonmonetary Support N.E.C." },
  { :code => 'U20', :description => "Science, General" },
  { :code => 'U21', :description => "Marine Science and Oceanography" },
  { :code => 'U30', :description => "Physical Sciences, Earth Sciences Research and Promotion" },
  { :code => 'U31', :description => "Astronomy" },
  { :code => 'U33', :description => "Chemistry, Chemical Engineering" },
  { :code => 'U34', :description => "Mathematics" },
  { :code => 'U36', :description => "Geology" },
  { :code => 'U40', :description => "Engineering and Technology Research, Services" },
  { :code => 'U41', :description => "Computer Science" },
  { :code => 'U42', :description => "Engineering" },
  { :code => 'U50', :description => "Biological, Life Science Research" },
  { :code => 'U99', :description => "Science and Technology Research Institutes, Services N.E.C." },
  { :code => 'V01', :description => "Alliance/Advocacy Organizations " },
  { :code => 'V02', :description => "Management & Technical Assistance " },
  { :code => 'V03', :description => "Professional Societies, Associations " },
  { :code => 'V05', :description => "Research Institutes and/or Public Policy Analysis " },
  { :code => 'V11', :description => "Single Organization Support " },
  { :code => 'V12', :description => "Fund Raising and/or Fund Distribution " },
  { :code => 'V19', :description => "Nonmonetary Support N.E.C." },
  { :code => 'V20', :description => "Social Science Institutes, Services" },
  { :code => 'V21', :description => "Anthropology, Sociology" },
  { :code => 'V22', :description => "Economics (as a social science)" },
  { :code => 'V23', :description => "Behavioral Science" },
  { :code => 'V24', :description => "Political Science" },
  { :code => 'V25', :description => "Population Studies" },
  { :code => 'V26', :description => "Law, International Law, Jurisprudence" },
  { :code => 'V30', :description => "Interdisciplinary Research" },
  { :code => 'V31', :description => "Black Studies" },
  { :code => 'V32', :description => "Women's Studies" },
  { :code => 'V33', :description => "Ethnic Studies" },
  { :code => 'V34', :description => "Urban Studies" },
  { :code => 'V35', :description => "International Studies" },
  { :code => 'V36', :description => "Gerontology (as a social science)" },
  { :code => 'V37', :description => "Labor Studies" },
  { :code => 'V99', :description => "Social Science Research Institutes, Services N.E.C." },
  { :code => 'W01', :description => "Alliance/Advocacy Organizations          " },
  { :code => 'W02', :description => "Management & Technical Assistance " },
  { :code => 'W03', :description => "Professional Societies, Associations " },
  { :code => 'W05', :description => "Research Institutes and/or Public Policy Analysis " },
  { :code => 'W11', :description => "Single Organization Support " },
  { :code => 'W12', :description => "Fund Raising and/or Fund Distribution " },
  { :code => 'W19', :description => "Nonmonetary Support N.E.C." },
  { :code => 'W20', :description => "Government and Public Administration" },
  { :code => 'W22', :description => "Public Finance, Taxation, Monetary Policy" },
  { :code => 'W24', :description => "Citizen Participation" },
  { :code => 'W30', :description => "Military, Veterans' Organizations" },
  { :code => 'W40', :description => "Public Transportation Systems, Services" },
  { :code => 'W50', :description => "Telephone, Telegraph and Telecommunication Services" },
  { :code => 'W60', :description => "Financial Institutions, Services (Non-Government Related)" },
  { :code => 'W61', :description => "Credit Unions" },
  { :code => 'W70', :description => "Leadership Development" },
  { :code => 'W80', :description => "Public Utilities" },
  { :code => 'W90', :description => "Consumer Protection, Safety" },
  { :code => 'W99', :description => "Public, Society Benefit - Multipurpose and Other N.E.C." },
  { :code => 'X01', :description => "Alliance/Advocacy Organizations " },
  { :code => 'X02', :description => "Management & Technical Assistance " },
  { :code => 'X03', :description => "Professional Societies, Associations " },
  { :code => 'X05', :description => "Research Institutes and/or Public Policy Analysis " },
  { :code => 'X11', :description => "Single Organization Support " },
  { :code => 'X12', :description => "Fund Raising and/or Fund Distribution " },
  { :code => 'X19', :description => "Nonmonetary Support N.E.C." },
  { :code => 'X20', :description => "Christian" },
  { :code => 'X21', :description => "Protestant" },
  { :code => 'X22', :description => "Roman Catholic" },
  { :code => 'X30', :description => "Jewish" },
  { :code => 'X40', :description => "Islamic" },
  { :code => 'X50', :description => "Buddhist" },
  { :code => 'X70', :description => "Hindu" },
  { :code => 'X80', :description => "Religious Media, Communications Organizations " },
  { :code => 'X81', :description => "Religious Film, Video" },
  { :code => 'X82', :description => "Religious Television" },
  { :code => 'X83', :description => "Religious Printing, Publishing" },
  { :code => 'X84', :description => "Religious Radio " },
  { :code => 'X90', :description => "Interfaith Issues" },
  { :code => 'X99', :description => "Religion Related, Spiritual Development N.E.C." },
  { :code => 'Y01', :description => "Alliance/Advocacy Organizations          " },
  { :code => 'Y02', :description => "Management & Technical Assistance " },
  { :code => 'Y03', :description => "Professional Societies, Associations " },
  { :code => 'Y05', :description => "Research Institutes and/or Public Policy Analysis " },
  { :code => 'Y11', :description => "Single Organization Support " },
  { :code => 'Y12', :description => "Fund Raising and/or Fund Distribution " },
  { :code => 'Y19', :description => "Nonmonetary Support N.E.C." },
  { :code => 'Y20', :description => "Insurance Providers, Services" },
  { :code => 'Y22', :description => "Local Benevolent Life Insurance Associations, Mutual Irrigation and Telephone Companies, and Like Organizations" },
  { :code => 'Y23', :description => "Mutual Insurance Company or Association" },
  { :code => 'Y24', :description => "Supplemental Unemployment Compensation" },
  { :code => 'Y25', :description => "State-Sponsored Worker's Compensation Reinsurance Organizations" },
  { :code => 'Y30', :description => "Pension and Retirement Funds" },
  { :code => 'Y33', :description => "Teachers Retirement Fund Association" },
  { :code => 'Y34', :description => "Employee Funded Pension Trust" },
  { :code => 'Y35', :description => "Multi-Employer Pension Plans" },
  { :code => 'Y40', :description => "Fraternal Beneficiary Societies" },
  { :code => 'Y42', :description => "Domestic Fraternal Societies" },
  { :code => 'Y43', :description => "Voluntary Employees Beneficiary Associations (Non-Government)" },
  { :code => 'Y44', :description => "Voluntary Employees Beneficiary Associations (Government) " },
  { :code => 'Y50', :description => "Cemeteries, Burial Services" },
  { :code => 'Y99', :description => "Mutual/Membership Benefit Organizations, Other N.E.C." },
  { :code => 'Z99', :description => "Unknown" },
].map do |ntee|
  Ntee.create ntee
end
